# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='banker.Account', to='banker.Player'),
        ),
        migrations.AddField(
            model_name='account',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banker.Game'),
        ),
        migrations.AddField(
            model_name='account',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banker.Player'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payee_account', to='banker.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payer_account', to='banker.Account'),
            preserve_default=False,
        ),
    ]
