# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0002_auto_20170424_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('game', 'player')]),
        ),
    ]
